CREATE TABLE USERS (
	ID	MEDIUMINT NOT NULL AUTO_INCREMENT,
	NAME VARCHAR(50) NOT NULL,
	EMAIL VARCHAR(100) NOT NULL UNIQUE,
	PASSWORD VARCHAR(50) NOT NULL,
	CODERDOJO VARCHAR(50),
	SESSION_HASH VARCHAR(100),
	PRIMARY KEY (ID)
)